apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-recreate
spec:
  replicas: 5
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: app-recreate
    spec:
      containers:
      - name: app-recreate
        image: arungupta/app-upgrade:v1
        ports:
        - containerPort: 8080
