AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation Template to create S3 bucket for central logging
Parameters:
  BucketName:
    Type: String
    Default: ''
    Description: Central logging bucket name
Resources:
  CentralLoggingBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
      LifecycleConfiguration:
        Rules:
          - Id: ArchiveToGlacier
            Prefix: ''
            Status: Enabled
            Transitions:
              - TransitionInDays: '10'
                StorageClass: GLACIER
Outputs:
  CentralLogBucket:
    Description: Central log bucket
    Value: !Ref BucketName
    Export:
      Name: CentralLogBucketName
